# Generated by Django 4.2.20 on 2025-03-21 12:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('review', models.TextField()),
                ('review_url', models.URLField(blank=True, max_length=500, null=True)),
                ('platform', models.CharField(db_index=True, max_length=100)),
                ('general_category', models.CharField(db_index=True, max_length=200)),
                ('specific_category', models.CharField(db_index=True, max_length=200)),
                ('reason', models.TextField()),
                ('category', models.CharField(choices=[('improvement', 'Improvement'), ('complaint', 'Complaint'), ('praise', 'Praise')], db_index=True, max_length=20)),
            ],
        ),
    ]
