# Generated by Django 5.2 on 2025-04-07 06:32

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, default=None, dimensions=768, null=True),
        ),
    ]
